/*
  ⚠️ PLEASE DO NOT MODIFY THIS FILE!

All code is automatically generated by plugin `js-var-to-css-var`.
*/
export type ITheme1 =
  | '0'
  | '1'
  | '2'
  | '3'
  | '--color-red'
  | '--color-blue'
  | '--theme-light'
  | '--theme-dark'
  | '--font-size-xs'
  | '--font-size-md'
  | '--font-size-lg'

