/*
  ⚠️ PLEASE DO NOT MODIFY THIS FILE!

All code is automatically generated by plugin `js-var-to-css-var`.
*/
export type ITheme2 =
  | '--color-red'
  | '--color-blue'
  | '--pos-top'
  | '--theme-light'
  | '--theme-dark'
  | '--font-size-xs'
  | '--font-size-md'
  | '--font-size-lg'

