"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.__ESLINT_STR__ = exports.__CODE_GEN_COMMENT__ = void 0;
exports.__CODE_GEN_COMMENT__ = `/\*\n  ⚠️ PLEASE DO NOT MODIFY THIS FILE!\n\n` +
    `All code is automatically generated by plugin \`js-var-to-css-var\`.\n*\/`;
exports.__ESLINT_STR__ = `/\* eslint-disable \*/`;
