export const __CODE_GEN_COMMENT__ =
  `/\*\n  ⚠️ PLEASE DO NOT MODIFY THIS FILE!\n\n` +
  `All code is automatically generated by plugin \`js-var-to-css-var\`.\n*\/`;

export const __ESLINT_STR__ = `/\* eslint-disable \*/`;
