const fs = require('fs');
const path = require('path');

import { IJsKv, IJsVarToCssVarOpts } from './types';

export const genCss = async (jsKv: IJsKv, opts?: IJsVarToCssVarOpts) => {
  if (!opts?.outputCssPath) throw new Error('Missing opts.outputCssPath!');
  if (!opts?.cssScopeTag) throw new Error('Missing opts.cssScopeTag!');

  const __CODE_GEN_COMMENT__ =
    `/\*\n  ⚠️ PLEASE DO NOT MODIFY THIS FILE!\n\n` +
    `All code is automatically generated by plugin \`js-or-ts-var-to-css-or-less-var\`.\n*\/`;
  // const __ESLINT_STR__ = `/\* eslint-disable \*/`;

  let HEADER = `${__CODE_GEN_COMMENT__}\n${opts.cssScopeTag} {\n`;

  if (opts?.lessHeaderImport) {
    HEADER = `${__CODE_GEN_COMMENT__}\n\n` + `${opts.cssScopeTag} {\n`;
  }

  const FOOTER = `}\n`;
  let CONTENT = '';

  for (const k in jsKv) {
    if (!k) return;

    const v = jsKv[k];
    CONTENT += `  ${k}: ${v};\n`;
  }

  const RESULT = `${HEADER}${CONTENT}${FOOTER}`;

  await fs.mkdirSync(path.dirname(opts.outputCssPath), { recursive: true });
  await fs.writeFileSync(opts.outputCssPath, RESULT);
};
