const fs = require('fs');
const path = require('path');

import { IJsKv, IJsVarToCssVarOpts } from './types';

export const genLess = async (jsKv: IJsKv, opts?: IJsVarToCssVarOpts) => {
  if (!opts?.outputLessPath) throw new Error('Missing opts.outputLessPath!');

  const __CODE_GEN_COMMENT__ =
    `/\*\n  ⚠️ PLEASE DO NOT MODIFY THIS FILE!\n\n` +
    `All code is automatically generated by plugin \`js-or-ts-var-to-css-or-less-var\`.\n*\/`;
  // const __ESLINT_STR__ = `/\* eslint-disable \*/`;

  let HEADER = `${__CODE_GEN_COMMENT__}\n\n`;

  if (opts?.lessHeaderImport) {
    HEADER = `${__CODE_GEN_COMMENT__}\n${opts?.lessHeaderImport}\n\n`;
  }

  const FOOTER = ``;
  let CONTENT = '';

  for (const k in jsKv) {
    if (!k) return;

    const v = jsKv[k];
    CONTENT += `${k.replace('--', '@')}: ${v};\n`;
  }

  const RESULT = `${HEADER}${CONTENT}${FOOTER}`;

  await fs.mkdirSync(path.dirname(opts.outputLessPath), { recursive: true });
  await fs.writeFileSync(opts.outputLessPath, RESULT);
};
